name: Build and Publish to GitHub Packages

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2

      - name: Set up JDK 25
        uses: actions/setup-java@v5.2.0
        with:
          java-version: '25'
          distribution: 'corretto'

      - name: Extract version from tag
        run: echo "VERSION=${GITHUB_REF_NAME}" >> $GITHUB_ENV

      - name: Build with Gradle
        run: ./gradlew build

      - name: Publish to GitHub Packages
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ env.VERSION }}
